---
- name: Configure a CSR Router
  hosts: CSR
  vars:
    creds:
      username: admin
      password: cisco
      authorize: yes


  tasks:
    - name: apply config file to the router
      ios_config:
        provider: "{{ creds }}"
        authorize: yes
        src: "/Github/AnsibleNetExamples/CSR-Builder/cfg_files/CSR01.cfg"
